version: "3"
services:
  db:
    image: mysql:8.0.19
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: difficultpassword
      MYSQL_USER: me
      MYSQL_PASSWORD: 1234
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./db_data:/var/lib/mysql
